import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Website Layout",
  description: "Generated by create next app",
};

export default function WebsiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen w-screen flex justify-center items-center">{children}</div>
  );
}
